
atomicio:
  enabled: true
  port: 8308
  workerThreads: 4
  codec:          # 解码器类型
    type: protobuf    # 可选值: text, protobuf, mqtt ...
  cluster:        # 集群配置
    enabled: false # 是否开启集群
    type: redis   # 集群广播类型 可选值: redis, kafka, rocketmq ...
    redis:        # redis 连接信息
      uri: redis://localhost:6379
      username:
      password:
  ssl:             # SSL 配置
    enabled: true
    cert-chain-path: "classpath:server.crt"
    private-key-path: "classpath:server.key"