
atomicio:
  enabled: true
  port: 8308
  workerThreads: 4
  ip-security:    # ip 安全配置
    max-connect: 2          # 同一 ip 最大连接数
    rate-limit-count: 10    # 同一 ip 在 rate-limit-interval 秒内最大连接数
    rate-limit-interval: 60 # 同一 ip 速率限制的单位秒数
  overload-protect:    # 服务器过载保护配置
    enabled: true # 是否开启服务器过载保护
    total-connect: 2 # 单台服务器最大连接数
    queue-min-percent: 90 # 单台服务器IO事件队列最容量告警阈值 (百分比)
  codec:          # 解码器类型
    type: protobuf    # 可选值: text, protobuf, mqtt ...
    max-frame-length: 100
  cluster:        # 集群配置
    enabled: true # 是否开启集群
    type: redis   # 集群广播类型 可选值: redis, kafka, rocketmq ...
    redis:        # redis 连接信息
      uri: redis://localhost:6379
      username:
      password:
  ssl:             # SSL 配置
    enabled: true
    cert-chain-path: "classpath:server.crt"
    private-key-path: "classpath:server.key"